name: Merge en genereer JSON-bestanden

on:
  push:
    paths:
      - 'EDIT-opleidingen/*.json'
      - 'merge_jsons.py'
      - 'generate_smartlions.py'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Merge EDIT-opleidingen naar DEF-JobAt.json
        run: python merge_jsons.py

      - name: Genereer DEF-Smartlions.json op basis van DEF-JobAt.json
        run: python generate_smartlions.py

      - name: Commit gewijzigde bestanden
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add DEF-JobAt.json DEF-Smartlions.json
          if git diff --cached --quiet; then
            echo "Geen wijzigingen — niets te committen."
          else
            git commit -m "Update DEF-JobAt.json en DEF-Smartlions.json"
            git push
