name: Merge JSON bestanden

on:
  push:
    paths:
      - 'per-opleidingstype/*.json'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Merge JSON files
        run: python merge_jsons.py

      - name: Commit DEF-test.json
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add DEF-test.json
          git diff --cached --quiet || git commit -m "Update DEF-test.json na wijziging in /per-opleidingstype"
          git push
