name: Merge JSON bestanden

on:
  push:
    paths:
      - 'EDIT-opleidingen/*.json'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Merge JSON files
        run: python merge_jsons.py

      - name: Commit en push DEF-JobAt.json als die gewijzigd is
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add DEF-JobAt.json
          if git diff --cached --quiet; then
            echo "Geen wijzigingen in DEF-JobAt.json — commit overslaan."
          else
            git commit -m "Update DEF-JobAt.json na wijziging in /EDIT-opleidingen"
            git push || echo "Push mislukt (mogelijk wegens missies of branch-protectie)"
          fi
